### ISSUE TITLE
 Can't open the list websites file at XAttacker.pl line 95, <STDIN> line 1.

### ISSUE THREAD

**Issue by GEOXORlol** [Proxysec/XAttacker-3.0#1]
![1111](https://user-images.githubusercontent.com/76542625/103050921-76c10a80-458d-11eb-93ef-114f4b57d8de.PNG)

i installed perl and python3.9 and all package i need but not working any fix pls.

**Comment by Proxysec** [comment]
Um it says there is no requests lib so 
pip2 install requests

**Comment by GEOXORlol** [comment]
thank you
